docusaurus.config.js
Signed-off-by: Paul Pietkiewicz <paul@profian.com>
=> chore(logo): add netlify logo

.github/CODEOWNERS, .gitignore, README.md, hack/preview.sh, hack/production.sh, netlify.toml, package.json
- Update documentation
- Fix production deployment script
- Set netlify to default to using release documentation
- Add @platten and @bstrie to CODEOWNERS
=> chore(tweaks): assorted tweaks 

docs/Contributing/Debug.md, sidebars.js
Signed-off-by: bstrie <865233+bstrie@users.noreply.github.com>
=> docs: migrate debugging docs from enarx repo

docs/Technical/Attestation-Syscall.md, sidebars.js
Signed-off-by: bstrie <865233+bstrie@users.noreply.github.com>
=> docs: migrate get_attestation syscall docs from wiki

docs/WebAssembly/JavaScript.md
=> docs: update javascript guide

docs/Contributing/Coding-Style.md
Signed-off-by: bstrie <865233+bstrie@users.noreply.github.com>
=> docs: migrate style docs from enarx repo

docs/WebAssembly/Swift.md
Added a detailed explanation of Docker, its advantages and use cases.
=> docs : update Swift guide

sidebars.js
=> docs: add Swift tutorial to sidebar

package.json, versioned_staging/Install.md, yarn.lock
=> docs: bump Docusaurus to version beta.20

resources/2022-02-02-mentorship.md, resources/2022-02-10-intro-enarx.md, resources/2022-02-25-veracruz.md, resources/2022-03-11-exercism.md, resources/2022-03-18-suborbital.md, resources/2022-04-01-erica-brescia.md, resources/2022-04-09-fossasia.md, resources/2022-04-19-trust.md, src/pages/webinars.md
Reorganize webinars page and add past webinars to resources.
=> feat: update webinars

resources/2022-04-01-erica-brescia.md, resources/2022-04-12-enarx-0-4-0.md, resources/2022-04-19-trust.md, resources/2022-04-21-enarx-wasm.md, resources/2022-05-03-macos-raspberrypi.md, resources/2022-05-10-enarx-0-5-0.md, resources/2022-05-10-enarx-pi.md, resources/2022-05-11-enarx-0-5-0.md
=> feat: add release and blog posts to Resources

src/pages/cryptle.md
=> docs: fix some typos in the cryptle hack challenge

docs/Contributing/Introduction.md, src/pages/meetings.md
=> docs: update google meet link

package.json, versioned_staging/Install.md, yarn.lock
Bump Docusaurus to latest version
=> docs: bump Docusaurus to version 2.0.0-beta.21

resources/2022-04-01-erica-brescia.md, resources/2022-04-19-trust.md, resources/2022-05-16-wasi-networking.md, resources/2022-05-17-cryptle.md, resources/2022-05-17-wasm-day.md, resources/2022-05-25-enarx-100-tutorials.md, src/pages/events.mdx
Add Wasm Day activities to Resources
- Wasm Day Recap
- WASI Networking
- Cryptle
- Wasm Builders (100 tutorials)
=> docs: add wasm day to resources

.gitignore, hack/preview.sh, hack/production.sh, sidebars.js
Signed-off-by: Paul Pietkiewicz <paul@profian.com>
=> feat: add menu item for Enarx_toml documentation

override/Quickstart.mdx
Signed-off-by: Paul Pietkiewicz <paul@profian.com>
=> release: update Quickstart to 0.6.0

docs/Credentials.md, versioned_staging/Credentials.md, versioned_staging/Running/Publish.md
=> fix: run hack/production.sh

package.json, yarn.lock
Updating Docusaurus to latest version (v.2.0.0-rc1)
=> docs: bump Docusaurus to v.2.0.0-rc1

docs/Contributing/Outreach.md, src/pages/meetings.md
=> docs: update outreach meeting

src/pages/2022-07-26-sgx.md, src/pages/events.mdx
=> docs: add SGX community day

resources/authors.yml, src/pages/2022-08-12-defcon.md, src/pages/2022-08-13-defcon.md, src/pages/events.mdx
=> docs: add defcon talks

src/pages/2022-08-13-defcon-cryptle.md, src/pages/2022-08-13-defcon-enarx.md, src/pages/events.mdx
Both presentations are confirmed for Aug 13th.
=> docs: update defcon date

docs/Start/TEE.md
Just adding some more clarity to the description.
I think saying 'these pages are not accessible' is not the best way to put it.
Thanks!
=> Minor change in the description of a TEE's working.

package.json, yarn.lock
=> docs: bump docusaurus to version 2.0.1

resources/2022-08-12-defcon-enarx.md
=> docs: fix defcon title

package.json, yarn.lock
Bump Docusaurus to latest version
=> fix: bump docusaurus to 2.1.0

resources/2022-08-03-new-stack.md, resources/2022-08-22-try-enarx.md
Add Try Enarx article and blog post
=> feat: add new article and blog posts

docusaurus.config.js, src/components/HomepageGuide.js, src/pages/index.js
Add Download and Try Enarx buttons to homepage. Partially addresses #76 
=> docs: add download/try enarx buttons

docs/WebAssembly/AssemblyScript.md, docs/WebAssembly/C++.md, docs/WebAssembly/C.md, docs/WebAssembly/Golang.md, docs/WebAssembly/Grain.md, docs/WebAssembly/JavaScript.md, docs/WebAssembly/Python.md, docs/WebAssembly/Ruby.md, docs/WebAssembly/Rust.md, docs/WebAssembly/Swift.md, docs/WebAssembly/Zig.md, docs/WebAssembly/dotnet.md
Synchronize the examples from the WebAssembly Guide with those from Codex. 
=> docs: sync wasm guide and codex

docs/WebAssembly/Introduction.md
=> docs: update wasm matrix

docs/WebAssembly/Java.md
=> docs: add Java example to the Wasm Guide

docs/WebAssembly/Java.md
=> docs: fix typos in the Java example

docusaurus.config.js, package.json, yarn.lock
Bump to latest version of Docusaurus (v2.2)
=> docs: bump to docusaurus v2.2

docs/WebAssembly/Introduction.md, sidebars.js
=> docs: reorder languages in wasm guide

docs/WebAssembly/AssemblyScript.md, docs/WebAssembly/C++.md, docs/WebAssembly/C.md, docs/WebAssembly/Golang.md, docs/WebAssembly/Grain.md, docs/WebAssembly/Introduction.md, docs/WebAssembly/Java.md, docs/WebAssembly/JavaScript.md, docs/WebAssembly/Python.md, docs/WebAssembly/Ruby.md, docs/WebAssembly/Rust.md, docs/WebAssembly/Swift.md, docs/WebAssembly/TypeScript.md, docs/WebAssembly/Zig.md, docs/WebAssembly/dotnet.md
=> docs: update all codex links in the wasm guide

resources/2022-09-23-try-enarx.md, resources/2022-09-28-cncf.md, resources/2022-10-26-cc.md, resources/2022-11-01-wasi.md
=> docs: add new blog posts to resources

resources/2022-10-01-confidential-computing.md, resources/2022-10-10-insider-risk.md, resources/2022-10-20-runtime-isolation.md
=> docs: add white papers

resources/2022-10-01-insider-risk.md, resources/2022-10-05-whats-confidential-computing.md, resources/2022-10-10-runtime-isolation.md, resources/2022-10-15-confidential-vms.md, resources/2022-10-20-wasm-security.md, resources/2022-10-25-privacy-enhancing-technologies.md, resources/2022-10-26-whats-confidential-computing.md, resources/2022-10-30-intro-confidential-computing.md
Add all white papers published so far at Profian
=> docs: add whitepapers

resources/2022-11-08-wasi.md
=> docs: add WASI blog post

docs/Clouds.md
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
=> Add Alibaba Cloud SGX info

docusaurus.config.js
=> docs: add VS Code to menu

docs/Networking.md
Add networking demos from Semester of Code and fix TCP Echo url.
=> docs: add networking examples from Semester of Code

docs/WebAssembly/Introduction.md
=> docs: simplify wasm guide

resources/2022-11-29-remote-attestation.md, resources/2022-12-14-unlock-cloud.md, resources/2022-12-19-confidential-vms.md, resources/2022-12-22-webassembly-23.md
=> feat: add latest blog posts from Enarx and Profian

docusaurus.config.js, yarn.lock
=> feat: add Google Analytics

resources/2023-01-16-enarx-0-7-0.md, resources/authors.yml
Signed-off-by: Dmitri Pal <dmitri@profian.com>
This PR creates a link between the Enarx website and the blog announcing the 0.7.0 Enarx release.
**Please do not merge before the blog is live.**
=> doc: create a link to release blog on the website

src/pages/2023-02-04-fosdem.md
add Roman's talk "Building a secure network of trusted applications on untrusted hosts"
=> feat: update fosdem talks

src/pages/2023-02-08-stateofopen.md
add Mike's talk "What's the big deal with Confidential Computing"
=> feat: add talk at State of Open Con

src/pages/2023-02-01-securitycon.md
add Nathaniel's talk at SecurityCon
=> docs: add securitycon talk

src/pages/2023-02-05-fosdem.md, src/pages/events.mdx
remove Shmoocon
add SecurityCon, FOSDEM, State of Open Con
=> docs: update events for february 2023

docs/WebAssembly/dotnet.md
Add the following demos:
- GreenhouseMonitor
- ICU Monitor
- Confidential Trading
=> docs: add .NET demos

package.json, yarn.lock
=> feat: bump docusaurus to 2.3.1

docs/Practices/Design-Practices.md, docs/Practices/Document-Properties-Convention.md, docs/Practices/Project-Management-Practices.md, docs/Practices/Release-process-instructions.md
Signed-off-by: Dmitri Pal <dmitri@profian.com>
Publishing development practices stored in HackMD https://hackmd.io/team/enarx?nav=overview to Github.
=> doc: publish practices to GitHub

package.json, yarn.lock
=> docs: update to latest docusaurus

docs/WebAssembly/JavaScript.md
update the repository URL for javy
=> Update JavaScript docs for compiling to webassembly
